version: '3'

services:
    postgres:
        image: postgres:10.4-alpine
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3.7-alpine
        restart: always
        volumes:
            - rabbitmq:/var/lib/rabbitmq

    worker:
        build: docker
        restart: always
        command: bin/console messenger:consume-messages --memory-limit=16M
        working_dir: /app
        volumes:
            - .:/app
        depends_on:
            - postgres
            - rabbitmq

volumes:
    postgres:
    rabbitmq:
